export const apiLogin = "User/Login";
export const apiUpdateProfile = "Customer/UpdateProfile";
export const apiGetListWishList = "Wishlist/GetWishlistList";
export const apiAddWishList = "WishList/Create";
export const apiDeleteWishList = "Wishlist/Delete";
export const apigetCurrentUser = "User/GetProfile";
export const apiGetFeedback = "Feedback/GetFeedbacksHistory";
export const apiCreateFeedback = "Feedback/Create";
export const apiDeleteFeedback = "Feedback/Delete";
export const apiGetListRestaurants =
	"CategoryRestaurant/GetAllCategoryRestaurants";
export const apiRegisterRestaurant = "User/RegisterRestaurant";
export const apiUpdateDesRestaurant = "Restaurant/UpdateDescription";
export const apiForgotPassword = "User/ForgotPassword";
export const apiVerifyOTP = "User/VerifyOTP";
export const apiResetPassword = "User/ResetPassword";
export const apiChangePassword = "User/ChangePassword";
export const apiGetMenu = "Menu/GetMenuListForCustomer";
export const apiGetTable = "RestaurantTables/GetAvailableTables";
export const apiCalTotalOrder = "Order/CalculateTotalAmountFreDiscount";
export const apiGetAllDiscount = "Discount/GetAvailableDiscount";
export const apiCreateOrder = "Order/Create";
export const apiGetOrderHistory = "Order/GetOrdeHistoryForCustomer";
export const apiViewOrderDetail = "Order/GetOrder";
export const apiPaidOrder = "Order/PaidOrder";
export const apiGetWalletInfo = "Wallet/GetWalletInfo";
export const apiAddOTP = "Wallet/AddOTP";
export const apiCreateOrUpdateBank = "Wallet/CreateOrUpdateBank";
export const apiDeposit = "WalletTransaction/Recharge";
export const apiCheckRecharge = "WalletTransaction/CheckRecharge";
export const apiRegisterCustomer = "User/RegisterCustomer";
export const apiUpdateResInfor = "Restaurant/UpdateRestaurantInfo";
export const apiCheckEmail = "User/CheckExistEmail";
export const apiGetTransactionHistory =
	"WalletTransaction/GetWalletTransactionList";
export const apiWithdraw = "WalletTransaction/Withdraw";
export const apiLoginGG = "User/LoginWithGoogle";
export const apiCheckPaymentOrder = "Order/CheckPayment";
export const apiCancelOrder = "Order/CancelOrder";
export const apiGetRestaurantDashboard = "Dashboard/GetDashboardRestaurant";
export const apiChangeMenus = "Order/ChangeMenus";
export const apiGetAllOrderByRestaurant = "Order/GetOrderListForRestaurant";
export const apiUpdateOrderForConfirm = "Order/UpdateStatus";
export const apiCreateTableOrder = "Order/CreateOrderTable";
export const apiUpdateRestaurantProfile = "Restaurant/UpdateRestaurantInfo";
export const apiGetAllTableLazy = "TableBookingSchedule/GetTableBookingScheduleList";
export const apiGetAllTableScheduleList = "RestaurantTables/GetTableScheduleList";
export const apiCreateScheduleTable = "TableBookingSchedule/Create";
export const apiDeleteScheduleTable = "TableBookingSchedule/Delete";
export const apiGetAllImageRestaurant = "Image/GetImageList"
export const apiUpdatePolicy = "Restaurant/UpdateDiscountAndFee"
export const apiGetAllFeedbackByRestaurant = "Feedback/GetFeedbackListForRestaurant"


