export const apiGetAllBlog = "Blog/GetBlogListForAdmin"
export const apiGetCategoryBLog = "BlogGroup/GetBlogGroupList"
export const apiDeleteBlog = "Blog/Delete"
export const apiUpdateBlog = "Blog/Update"
export const apiCreateBlog = "Blog/Create"
export const apiGetAllUser = "User/GetAllUser"
